mysql: false
mysql-database: jdbc:mysql://localhost:3306/minecraft
mysql-user: root
mysql-password: root
mysql-table: banlist
auto-complete: true
messages:
  banMsgFailed: '&cPlayer &e%victim% &cis already banned!'
  unbanMsg: '&aSuccessfully unbanned player &e%victim%&a!'
  unbanMsgGlobal: '&e%victim% &6was unbanned by &e%player%&6!'
  unbanMsgFailed: '&cFailed to unban &e%victim%&c!'
  kickAllMsg: '%player% kicked everyone. Reason: %reason%'
  kickDefaultReason: '&eBoot Hammer has Spoken!'
  kickGobalDefaultRason: '&eGlobal kick'
  kickMsgVictim: 'You have been kicked by %player%. Reason: %reason%'
  kickMsgBroadcast: '&e%victim% &6was kicked by &e%player%&6. Reason: &e%reason%'
  kickMsgFailed: '&cKick failed: &6%victim% &cisn''t online.'
  banMsgVictim: 'You have been banned by %player%. Reason: %reason%'
  banMsgBroadcast: '&e%victim% &6was banned by &e%player%&6. Reason: &e%reason%'
  banDefaultReason: '&eBan Hammer has Spoken!'
  tempbanMsgVictim: 'You have been temp. banned by %player%. Reason: %reason%'
  tempbanMsgBroadcast: '&e%victim% &6was temp. banned by &e%player%&6. Reason: &e%reason%'
  LoginTempban: '&cYou are banned until &e%time%&c! Reason: &e%reason%'
  LoginBan: '&cYou are banned from this server! Reason: &e%reason%'
  LoginIPBan: '&cThis IP is banned!'
  badPlayerName: '&cBad player name!'
  playerNotOnline: '&cPlayer &e%player% &cis not online.'
  warnMsgBroadcast: '&cPlayer &e%player%&f received a warning from &c%kicker%&f:'
  warnMsgVictim: '&cYou have received a warning from &c%player%&f:'
  reloadMsg: '&aReloaded FigAdmin.'
  exportMsg: '&aExported banlist to banned-players.txt'
  playerBanned: '&cPlayer %player% is banned.'
  playerNotBanned: '&aPlayer %player% is not banned.'